
<h2>Rédiger un nouvel article</h2>

<form action="<?=buildUrl('/create');?>" method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label for="title">Titre</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Enter the title">   
    </div>
    <div class="form-group">
        <label for="content">Résumé</label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>    
    </div>

    <div class="form-group">
        <label for="author">Auteur</label>
        <input type="text" class="form-control" id="author" name="author" placeholder="author">
    </div>

    <div class="form-group">
        <label for="image">Image</label>
        <input type="text" class="form-control" id="image" name="image" placeholder="image">
    </div>

    <div class="form-group">
        <label for="category">Catégorie</label>
        <select name="category">
            <?php foreach($categories as $category): ?>
            <option value="<?=$category['id'];?>"><?=$category['name'];?></option>
            <?php endforeach; ?>
        </select>
    </div>   

    <button type="submit" class="btn buttonForm">Enregistrer</button>
</form>
    