<header>

<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link" href="<?= buildUrl('/');?>">My Blog<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= buildUrl('/create');?>">Create an article</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= buildUrl('/advancedSearch');?>">Recherche avancée</a>
    </li>
    </ul>

    <form class="form-inline my-2 my-lg-0" action="<?=buildUrl('/');?>" method="GET" enctype="multipart/form-data">
    <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Recherche</button>
    </form>
    </div>
</nav>

</header>

    <section>
        <h1 class="d-flex justify-content-center m-3">Extraits d' articles</h1>

    <p style="text-align:center;"><?= $message;?></p>    
        
    <div class="d-flex justify-content-center">
    <?php foreach($articles as $article): ?>

    <div class="card m-3" style="width: 18rem;">
            <img class="card-img-top" src="upload/img/<?=htmlspecialchars($article['image']);?>" alt="Card image cap">
        <div class="card-body">
        <h5 class="card-title"><?=htmlspecialchars($article['title']);?></h5>
        <h4 class="card-title"><?=htmlspecialchars($article['author']);?></h4>     
        <p class="card-text"><?=htmlspecialchars(mb_substr($article['content'], 0, 150, 'UTF-8'));?></p>
        <p>Sorti le : <time datetime="<?= htmlspecialchars($article['createdAt']);?>"><?= date('d/m/Y',strtotime(htmlspecialchars($article['article']))); ?></time></p>
            <a href="<?= buildUrl('/article', ['articleid'=> intval($article['articleid'])]);?>" class="btn buttonForm">Lire la suite</a>
        </div>
    </div>       
    <?php endforeach;?>
    </div>

    </section>