
    <h2 class="d-flex justify-content-center m-3">Modifier un article</h2>

    <form  action="<?=buildUrl('/update', ['articleid' => $article['articleid']]);?>" method="POST" enctype="multipart/form-data">

            <div class="form-group">
                <label for="title">Titre</label>
                <input type="text" class="form-control" id="title" name="title" value="<?=$article['title'];?>">
            </div>
            
            <div class="form-group">
                <label for="description">Contenu</label>
                <textarea id="content" name="content" ><?=$article['content'];?></textarea>
            </div>

            <div class="form-group">
                <label for="author">Auteur</label>
                <input type="text" class="form-control"  id="author" name="author" value="<?=$article['author'];?>">
            </div>

            <div class="form-group">
                <label for="image">Image</label>
                <input type="text" class="form-control"  id="image" name="image" value="<?=$article['image'];?>">
            </div>

            <div class="form-group">
                <label for="category">Catégorie</label>
                <select name="category">
                    <?php foreach($categories as $category): ?>
                        <!-- // est ce qiue la id de la category courante est egale à la catégorie de l'article -->
                        <?php $selected = $category['id'] === $article['categoryId'] ? 'selected' : ''; ?>
                        <option value="<?=$category['id'];?>"><?=$category['name'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
        <label for="keywords">Ajout de mot clefs </label>
        <select multiple="multiple" name="keywords[]">
            <?php foreach($keywords as $keyword): ?>
            <option value="<?=$keyword['id'];?>"><?=$keyword['word'];?></option>
            <?php endforeach; ?>
        </select>
        
    </div>   
            <input class="buttonForm" type="submit" value="modifier">
    </form>
